name: 'job_search_platform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'job_search_platform'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  job_search_platform:
    raw:
      +schema: raw
      +materialized: table
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: marts
      +materialized: table

# Variables
vars:
  project_start_date: '2025-01-01'

