"""Technical skills patterns for job enrichment.

This module contains a comprehensive set of technical skills that the enricher
service uses to identify skills mentioned in job descriptions.
Skills are organized by category, similar to SENIORITY_PATTERNS structure.
"""

from __future__ import annotations

# Technical skills patterns
# Each key represents a skill category, and the value is a list of patterns
# that indicate that skill in job descriptions/titles
TECHNICAL_SKILLS: dict[str, list[str]] = {
    "programming_languages": [
        "python",
        "java",
        "javascript",
        "js",
        "typescript",
        "ts",
        "c++",
        "cpp",
        "c#",
        "csharp",
        "go",
        "golang",
        "rust",
        "ruby",
        "php",
        "swift",
        "kotlin",
        "scala",
        "r",
        "matlab",
        "perl",
        "shell",
        "bash",
        "powershell",
    ],
    "web_technologies": [
        "html",
        "html5",
        "css",
        "css3",
        "react",
        "react.js",
        "angular",
        "angularjs",
        "vue",
        "vue.js",
        "node.js",
        "nodejs",
        "express",
        "express.js",
        "django",
        "flask",
        "spring",
        "spring boot",
        "spring framework",
        "asp.net",
        "laravel",
        "rails",
        "ruby on rails",
        "next.js",
        "nextjs",
        "nuxt",
        "svelte",
        "backend",
        "frontend",
        "full stack",
        "fullstack",
    ],
    "databases": [
        "sql",
        "postgresql",
        "postgres",
        "mysql",
        "mongodb",
        "mongo",
        "redis",
        "elasticsearch",
        "cassandra",
        "oracle",
        "oracle database",
        "sql server",
        "microsoft sql server",
        "dynamodb",
        "neo4j",
        "couchdb",
        "sqlite",
        "mariadb",
        "clickhouse",
        "influxdb",
        "timescaledb",
        "cockroachdb",
    ],
    "cloud_platforms": [
        "aws",
        "amazon web services",
        "azure",
        "microsoft azure",
        "gcp",
        "google cloud platform",
        "google cloud",
    ],
    "aws_services": [
        "s3",
        "amazon s3",
        "ec2",
        "amazon ec2",
        "lambda",
        "aws lambda",
        "rds",
        "amazon rds",
        "sagemaker",
        "amazon sagemaker",
        "sns",
        "amazon sns",
        "sqs",
        "amazon sqs",
        "cloudwatch",
        "amazon cloudwatch",
        "iam",
        "aws iam",
        "vpc",
        "amazon vpc",
        "eks",
        "amazon eks",
        "ecs",
        "amazon ecs",
        "fargate",
        "aws fargate",
        "glue",
        "aws glue",
        "athena",
        "amazon athena",
        "emr",
        "amazon emr",
        "kinesis",
        "amazon kinesis",
    ],
    "azure_services": [
        "azure functions",
        "azure data factory",
        "azure databricks",
        "azure synapse",
        "azure sql",
        "azure storage",
        "azure devops",
        "azure kubernetes service",
        "aks",
    ],
    "gcp_services": [
        "bigquery",
        "google bigquery",
        "cloud functions",
        "cloud run",
        "cloud storage",
        "cloud sql",
        "dataproc",
        "dataflow",
        "composer",
        "gke",
    ],
    "container_orchestration": [
        "docker",
        "kubernetes",
        "k8s",
    ],
    "infrastructure_as_code": [
        "terraform",
        "cloudformation",
        "aws cloudformation",
        "pulumi",
        "ansible",
    ],
    "cicd": [
        "jenkins",
        "ci/cd",
        "cicd",
        "automation",
        "git",
        "github",
        "gitlab",
        "circleci",
        "travis",
        "github actions",
        "azure pipelines",
        "cloud build",
    ],
    "data_processing": [
        "spark",
        "apache spark",
        "hadoop",
        "apache hadoop",
        "kafka",
        "apache kafka",
        "airflow",
        "apache airflow",
        "dbt",
        "data build tool",
        "flink",
        "apache flink",
        "storm",
        "apache storm",
        "presto",
        "trino",
        "apache beam",
        "data modeling",
        "transformation",
        "data transformation",
        "modeling",
    ],
    "data_warehouses": [
        "snowflake",
        "databricks",
        "redshift",
        "amazon redshift",
        "aws redshift",
        "bigquery",
        "google bigquery",
        "synapse",
        "azure synapse",
        "delta lake",
        "iceberg",
        "apache iceberg",
    ],
    "bi_visualization": [
        "tableau",
        "power bi",
        "powerbi",
        "looker",
        "qlik",
        "qlikview",
        "qlik sense",
        "microstrategy",
        "domo",
        "metabase",
        "visualization",
        "data visualization",
        "dashboards",
    ],
    "python_libraries": [
        "pandas",
        "numpy",
        "scikit-learn",
        "sklearn",
        "tensorflow",
        "pytorch",
        "keras",
        "scipy",
        "matplotlib",
        "seaborn",
        "plotly",
    ],
    "ml_ai": [
        "ml",
        "machine learning",
        "deep learning",
        "ai",
        "artificial intelligence",
        "nlp",
        "natural language processing",
        "computer vision",
        "data science",
        "data engineering",
        "bi",
        "business intelligence",
        "analytics",
        "pipelines",
        "etl",
        "elt",
    ],
    "other_technologies": [
        "linux",
        "unix",
        "rest",
        "graphql",
        "microservices",
        "api",
        "agile",
        "scrum",
        "jira",
        "confluence",
        "slack",
        "figma",
        "adobe",
        "photoshop",
    ],
}

# Flattened set of all skills for backward compatibility
# This allows the enricher to iterate over all skills without category structure
_ALL_SKILLS = set()
for skills_list in TECHNICAL_SKILLS.values():
    _ALL_SKILLS.update(skills_list)

# Export both the structured dict and flattened set
__all__ = ["TECHNICAL_SKILLS", "get_all_skills"]


def get_all_skills() -> set[str]:
    """
    Get a flattened set of all technical skills.

    Returns:
        Set of all skill patterns (for backward compatibility with code that
        expects TECHNICAL_SKILLS to be iterable)
    """
    return _ALL_SKILLS.copy()
