"""Technical skills patterns for job enrichment.

This module contains a comprehensive set of technical skills that the enricher
service uses to identify skills mentioned in job descriptions.
"""

# Common technical skills to look for
TECHNICAL_SKILLS = {
    # Programming Languages
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "go",
    "rust",
    "ruby",
    "php",
    "swift",
    "kotlin",
    "scala",
    "r",
    "matlab",
    "perl",
    "shell",
    "bash",
    # Web Technologies
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "node.js",
    "express",
    "django",
    "flask",
    "spring",
    "asp.net",
    "laravel",
    "rails",
    "next.js",
    "nuxt",
    "svelte",
    # Databases
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "elasticsearch",
    "cassandra",
    "oracle",
    "sql server",
    "dynamodb",
    "neo4j",
    "couchdb",
    # Cloud & DevOps
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "jenkins",
    "ci/cd",
    "git",
    "github",
    "gitlab",
    "circleci",
    "travis",
    "github actions",
    # Data & Analytics
    "spark",
    "hadoop",
    "kafka",
    "airflow",
    "dbt",
    "tableau",
    "power bi",
    "looker",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "keras",
    "ml",
    "machine learning",
    "deep learning",
    "data science",
    "data engineering",
    # Other Technologies
    "linux",
    "unix",
    "rest",
    "graphql",
    "microservices",
    "api",
    "agile",
    "scrum",
    "jira",
    "confluence",
    "slack",
    "figma",
    "adobe",
    "photoshop",
}
