version: 2

sources:
  - name: marts
    description: Marts layer tables
    schema: marts
    tables:
      - name: job_campaigns
        description: Stores job campaigns that drive extraction and ranking. Populated exclusively via Campaign Management UI.
        columns:
          - name: campaign_id
            description: Unique campaign identifier
            data_type: integer
          - name: campaign_name
            description: Human-readable campaign name
            data_type: varchar
          - name: is_active
            description: Whether this campaign is active
            data_type: boolean
          - name: query
            description: Job search query (job title/keywords)
            data_type: varchar
          - name: location
            description: Job location preference
            data_type: varchar
          - name: country
            description: Country code (e.g., 'ca', 'us')
            data_type: varchar
          - name: date_window
            description: Date window for job postings (e.g., 'today', 'week', '7d')
            data_type: varchar
          - name: email
            description: Email address for notifications
            data_type: varchar
          - name: skills
            description: Preferred skills (semicolon-separated)
            data_type: varchar
          - name: min_salary
            description: Minimum salary preference
            data_type: numeric
          - name: max_salary
            description: Maximum salary preference
            data_type: numeric
          - name: currency
            description: "Currency code for salary preferences (e.g., USD, CAD, EUR)"
            data_type: varchar
          - name: remote_preference
            description: "Remote work preference (comma-separated: remote, hybrid, onsite)"
            data_type: varchar
          - name: seniority
            description: "Preferred seniority level (comma-separated: entry, mid, senior, lead)"
            data_type: varchar
          - name: company_size_preference
            description: "Company size preference (comma-separated ranges)"
            data_type: varchar
          - name: employment_type_preference
            description: "Employment type preference (comma-separated: FULLTIME, PARTTIME, etc.)"
            data_type: varchar
          - name: ranking_weights
            description: "Custom ranking weights as JSONB (percentages, must sum to 100%)"
            data_type: jsonb
          - name: created_at
            description: Timestamp when campaign was created
            data_type: timestamp
          - name: updated_at
            description: Timestamp when campaign was last updated
            data_type: timestamp
          - name: total_run_count
            description: Total number of times this campaign has been processed
            data_type: integer
          - name: last_run_at
            description: Timestamp of last campaign run
            data_type: timestamp
          - name: last_run_status
            description: Status of last run (e.g., 'success', 'failed', 'never')
            data_type: varchar
          - name: last_run_job_count
            description: Number of jobs found in last run
            data_type: integer
        tests:
          - salary_range_validation:
              min_salary_column: min_salary
              max_salary_column: max_salary

models:
  - name: job_campaigns
    description: Ephemeral model for dbt lineage. References marts.job_campaigns table created by docker/init/02_create_tables.sql. Campaigns are created and managed exclusively via the Campaign Management UI.
    config:
      materialized: ephemeral

  - name: dim_companies
    description: Dimension table for companies. One row per distinct company. Built from staging.glassdoor_companies with surrogate key company_key.
    columns:
      - name: company_key
        description: Surrogate key for company (hash of glassdoor_company_id and normalized name)
        tests:
          - not_null
          - unique
      - name: glassdoor_company_id
        description: Natural key from Glassdoor API
        tests:
          - not_null
      - name: normalized_company_name
        description: Normalized company name (lowercase, trimmed) for matching
      - name: company_name
        description: Company name from Glassdoor
      - name: rating
        description: Overall company rating from Glassdoor
      - name: industry
        description: Company industry

  - name: fact_jobs
    description: "Fact table for job postings. One row per job posting per campaign (composite key: jsearch_job_id, campaign_id). Built from staging.jsearch_job_postings joined to dim_companies."
    columns:
      - name: jsearch_job_id
        description: Natural key from JSearch API (part of composite primary key)
        tests:
          - not_null
      - name: campaign_id
        description: Foreign key to job_campaigns (part of composite primary key). Indicates which campaign extracted this job.
        tests:
          - not_null
          - relationships:
              to: ref('job_campaigns')
              field: campaign_id
      - name: company_key
        description: Foreign key to dim_companies
        tests:
          - relationships:
              to: ref('dim_companies')
              field: company_key
      - name: job_title
        description: Job title
        tests:
          - not_null
      - name: employer_name
        description: Original employer name from JSearch API (fallback when company not found in Glassdoor)
      - name: job_location
        description: Job location
      - name: job_employment_type
        description: "Employment type (string version, e.g., 'Full-time')"
      - name: job_employment_types
        description: "Employment types (JSONB array version, e.g., ['FULLTIME'])"
      - name: employment_types
        description: "Employment types (comma-separated string, e.g., 'FULLTIME,PARTTIME')"
      - name: apply_options
        description: Application options (JSONB)
      - name: job_apply_link
        description: Primary application link extracted from job_apply_link field or apply_options array
      - name: job_is_remote
        description: Whether job is remote
      - name: job_posted_at_datetime_utc
        description: Job posted datetime in UTC
      - name: extracted_skills
        description: "JSON array of extracted technical skills (populated by Enricher service)"
      - name: seniority_level
        description: "Seniority level extracted from job title/description: intern, junior, mid, senior, executive (populated by Enricher service)"
      - name: remote_work_type
        description: "Remote work type extracted from job description: remote, hybrid, onsite (populated by Enricher service)"
      - name: job_min_salary
        description: "Minimum salary (enriched from job description or from API)"
      - name: job_max_salary
        description: "Maximum salary (enriched from job description or from API)"
    tests:
      - salary_range_validation:
          min_salary_column: job_min_salary
          max_salary_column: job_max_salary
      - test_data_freshness:
          column_name: job_posted_at_datetime_utc
          max_age_days: 180
      - name: job_salary_period
        description: "Salary period: year, month, week, day, hour (enriched from job description or from API)"
      - name: job_salary_currency
        description: "Currency code: USD, CAD, EUR, GBP, or NULL (enriched from job description or from API)"
    tests:
      - assert_unique_combination:
          combination_of_columns:
            - jsearch_job_id
            - campaign_id

  - name: dim_ranking
    description: Ephemeral model for dbt lineage. References marts.dim_ranking table created by docker/init/02_create_tables.sql. Data is populated by the Ranker service (services/ranker/job_ranker.py), not by dbt transformations.
    config:
      materialized: ephemeral
    columns:
      - name: jsearch_job_id
        description: Foreign key to fact_jobs (part of composite key)
        tests:
          - not_null
          - composite_relationship:
              to: ref('fact_jobs')
              field: jsearch_job_id
              composite_fields:
                - jsearch_job_id
                - campaign_id
      - name: campaign_id
        description: Foreign key to job_campaigns (part of composite key)
        tests:
          - not_null
          - relationships:
              to: ref('job_campaigns')
              field: campaign_id
      - name: rank_score
        description: Ranking score (0-100)
        tests:
          - not_null
          - rank_score_range:
              column_name: rank_score
      - name: rank_explain
        description: JSON breakdown of ranking factors (Phase 3 feature)
      - name: ranked_at
        description: Timestamp when ranking was calculated
      - name: ranked_date
        description: Date when ranking was calculated
      - name: dwh_load_timestamp
        description: Data warehouse load timestamp
      - name: dwh_source_system
        description: Source system identifier

