-- ============================================================
-- Add ChatGPT Enrichment Columns to Staging Table
-- Migration script: 09_add_chatgpt_enrichment_columns.sql
-- Adds columns for ChatGPT-based enrichment to staging.jsearch_job_postings
-- ============================================================

-- Add ChatGPT enrichment columns to staging.jsearch_job_postings
-- These columns are nullable (backfill not required)
ALTER TABLE staging.jsearch_job_postings
    ADD COLUMN IF NOT EXISTS job_summary TEXT,
    ADD COLUMN IF NOT EXISTS chatgpt_extracted_skills JSONB,
    ADD COLUMN IF NOT EXISTS chatgpt_extracted_location VARCHAR(255),
    ADD COLUMN IF NOT EXISTS chatgpt_enriched_at TIMESTAMP;

-- Add comment to document the columns
COMMENT ON COLUMN staging.jsearch_job_postings.job_summary IS '2 sentence summary of the job posting, generated by ChatGPT';
COMMENT ON COLUMN staging.jsearch_job_postings.chatgpt_extracted_skills IS 'Skills extracted by ChatGPT (JSONB array of skill strings)';
COMMENT ON COLUMN staging.jsearch_job_postings.chatgpt_extracted_location IS 'Normalized location extracted by ChatGPT';
COMMENT ON COLUMN staging.jsearch_job_postings.chatgpt_enriched_at IS 'Timestamp when ChatGPT enrichment was completed';

-- Update enrichment_status JSONB to include ChatGPT enrichment flag
-- This allows tracking whether ChatGPT enrichment has been completed
-- Note: This is a no-op if the column doesn't exist yet (it's created by dbt)
-- We'll handle the enrichment_status update in the enricher service




